version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - web
      - db
      - cache
    networks:
      - app-network
  web:
    image: library/nginx:1-alpine
    restart: unless-stopped
    tty: true
    networks:
      - app-network
  db:
    image: library/postgres:12-alpine
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
  cache:
    image: library/redis:5-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
